#include "TComplex.h"
#include "TString.h"
#include <vector>
#include <TVector3.h>
#include "TDirectory.h"
#include "TTree.h"
#include "TFile.h"
#include "TH1.h"
#include "TMath.h"
#include <fstream>
#include <iostream>

void epos_data_comp(){

TH1D::SetDefaultSumw2();

   TH1D* vxHist;
   TH1D* vyHist;
   TH1D* vzHist;
   TH1D* generalTracksHist;
   TH1D* ptHist;
   TH1D* etaHist;
   TH1D* phiHist;
   TH1D* hHF;
   TH1D* hHFplus;
   TH1D* hHFminus;
   TH2D* hetaVSphi;
   TH1D* hdzOerr;
   TH1D* hd0Oerr;
   TH1D* hpterrOpt;

   TH1D* vxHistData;
   TH1D* vyHistData;
   TH1D* vzHistData;
   TH1D* generalTracksHistData;
   TH1D* ptHistData;
   TH1D* etaHistData;
   TH1D* phiHistData;
   TH1D* hHFData;
   TH1D* hHFplusData;
   TH1D* hHFminusData;
   TH2D* hetaVSphiData;
   TH1D* hdzOerrData;
   TH1D* hd0OerrData;
   TH1D* hpterrOptData;

  TFile* inFileMC = new TFile("../flow_Validation_EPOS_pPb_10k.root");
  vxHist = (TH1D*)inFileMC->Get(Form("demo/vxhist"));  
  vyHist = (TH1D*)inFileMC->Get(Form("demo/vyhist"));  
  vzHist = (TH1D*)inFileMC->Get(Form("demo/vzhist"));  
  generalTracksHist = (TH1D*)inFileMC->Get(Form("demo/generaltrackshist"));  
  ptHist = (TH1D*)inFileMC->Get(Form("demo/pthist"));  
  etaHist = (TH1D*)inFileMC->Get(Form("demo/etahist"));  
  phiHist = (TH1D*)inFileMC->Get(Form("demo/phihist"));  
  hHF = (TH1D*)inFileMC->Get(Form("demo/hfhist"));  
  hHFplus = (TH1D*)inFileMC->Get(Form("demo/hfplushist"));  
  hHFminus = (TH1D*)inFileMC->Get(Form("demo/hfminushist"));  
  hetaVSphi = (TH2D*)inFileMC->Get(Form("demo/hetavsphi"));  
  hdzOerr = (TH1D*)inFileMC->Get(Form("demo/hdzoerr"));  
  hd0Oerr = (TH1D*)inFileMC->Get(Form("demo/hd0oerr"));  
  hpterrOpt = (TH1D*)inFileMC->Get(Form("demo/hpterropt"));  

  TFile* inFileData = new TFile("../flow_Validation_data_pPb_10k.root");
  vxHistData = (TH1D*)inFileData->Get(Form("demo/vxhist"));
  vyHistData = (TH1D*)inFileData->Get(Form("demo/vyhist"));
  vzHistData = (TH1D*)inFileData->Get(Form("demo/vzhist"));
  generalTracksHistData = (TH1D*)inFileData->Get(Form("demo/generaltrackshist"));
  ptHistData = (TH1D*)inFileData->Get(Form("demo/pthist"));
  etaHistData = (TH1D*)inFileData->Get(Form("demo/etahist"));
  phiHistData = (TH1D*)inFileData->Get(Form("demo/phihist"));
  hHFData = (TH1D*)inFileData->Get(Form("demo/hfhist"));
  hHFplusData = (TH1D*)inFileData->Get(Form("demo/hfplushist"));
  hHFminusData = (TH1D*)inFileData->Get(Form("demo/hfminushist"));
  hetaVSphiData = (TH2D*)inFileData->Get(Form("demo/hetavsphi"));
  hdzOerrData = (TH1D*)inFileData->Get(Form("demo/hdzoerr"));
  hd0OerrData = (TH1D*)inFileData->Get(Form("demo/hd0oerr"));
  hpterrOptData = (TH1D*)inFileData->Get(Form("demo/hpterropt"));

//vertex
  TCanvas *c01 = new TCanvas("c01","c01",1,1,770,660);
  c01->SetFillColor(10);
  c01->SetFrameFillColor(0);
  c01->SetFrameBorderSize(0);
  c01->SetFrameBorderMode(0);
  c01->SetLeftMargin(0.15);
  c01->SetBottomMargin(0.15);
  c01->SetTopMargin(0.02);
  c01->SetRightMargin(0.02);
  c01->Divide(2,2);
  gStyle->SetOptStat(0);
  c01->SetTicks(-1);
  //c01->SetLogx();
  //c01->SetGridx();
  c01->cd(1);
  vxHist->SetMaximum(vxHist->GetMaximum()*1.2);
  vxHist->SetXTitle("vx (cm)");
  vxHist->SetYTitle("Events");
  vxHist->GetXaxis()->CenterTitle(1);
  vxHist->GetYaxis()->CenterTitle(1);
  vxHist->GetXaxis()->SetTitleOffset(1.);
  vxHist->GetYaxis()->SetTitleOffset(1.12);
  vxHist->GetXaxis()->SetTitleSize(0.048);
  vxHist->GetYaxis()->SetTitleSize(0.048);
  vxHist->Draw("HIST");
  vxHistData->SetLineColor(2);
  vxHistData->Draw("HIST same");
  TLatex *tex1= new TLatex(-0.35,vxHist->GetMaximum()*0.8,"MC");
  tex1->SetTextColor(1);
  tex1->SetTextSize(0.075);
  tex1->SetTextFont(42);
  tex1->Draw();
  TLatex *tex2= new TLatex(-0.35,vxHist->GetMaximum()*0.66,"DATA");
  tex2->SetTextColor(2);
  tex2->SetTextSize(0.075);
  tex2->SetTextFont(42);
  tex2->Draw();
  c01->cd(2);
  vyHist->SetMaximum(vyHist->GetMaximum()*1.2);
  vyHist->SetXTitle("vy (cm)");
  vyHist->SetYTitle("Events");
  vyHist->GetXaxis()->CenterTitle(1);
  vyHist->GetYaxis()->CenterTitle(1);
  vyHist->GetXaxis()->SetTitleOffset(1.);
  vyHist->GetYaxis()->SetTitleOffset(1.12);
  vyHist->GetXaxis()->SetTitleSize(0.048);
  vyHist->GetYaxis()->SetTitleSize(0.048);
  vyHist->Draw("HIST");
  vyHistData->SetLineColor(2);
  vyHistData->Draw("HIST same");
  c01->cd(3);
  vzHist->SetMaximum(vzHist->GetMaximum()*1.2);
  vzHist->SetXTitle("vz (cm)");
  vzHist->SetYTitle("Events");
  vzHist->GetXaxis()->CenterTitle(1);
  vzHist->GetYaxis()->CenterTitle(1);
  vzHist->GetXaxis()->SetTitleOffset(1.);
  vzHist->GetYaxis()->SetTitleOffset(1.12);
  vzHist->GetXaxis()->SetTitleSize(0.048);
  vzHist->GetYaxis()->SetTitleSize(0.048);
  vzHist->Draw();
  vzHistData->SetLineColor(2);
  vzHistData->Draw("HIST same");
  c01->SaveAs("plot_vertex_comp.pdf");
  c01->SaveAs("plot_vertex_comp.png");

//tracks
  TCanvas *c02 = new TCanvas("c02","c02",1,1,770,660);
  c02->SetFillColor(10);
  c02->SetFrameFillColor(0);
  c02->SetFrameBorderSize(0);
  c02->SetFrameBorderMode(0);
  c02->SetLeftMargin(0.15);
  c02->SetBottomMargin(0.15);
  c02->SetTopMargin(0.02);
  c02->SetRightMargin(0.02);
  c02->Divide(2,2);
  gStyle->SetOptStat(0);
  c02->SetTicks(-1);
  c02->cd(1);
  gPad->SetLogy();
  ptHist->SetMaximum(ptHist->GetMaximum()*8.2);
  ptHist->SetXTitle("p_{T} (GeV/c)");
  ptHist->SetYTitle("Tracks");
  ptHist->GetXaxis()->CenterTitle(1);
  ptHist->GetYaxis()->CenterTitle(1);
  ptHist->GetXaxis()->SetTitleOffset(0.95);
  ptHist->GetYaxis()->SetTitleOffset(1.12);
  ptHist->GetXaxis()->SetTitleSize(0.048);
  ptHist->GetYaxis()->SetTitleSize(0.048);
  ptHist->Draw("HIST");
  ptHistData->SetLineColor(2);
  ptHistData->Draw("HIST same");
  TLatex *tex1= new TLatex(5.35,ptHist->GetMaximum()*0.09,"MC");
  tex1->SetTextColor(1);
  tex1->SetTextSize(0.075);
  tex1->SetTextFont(42);
  tex1->Draw();
  TLatex *tex2= new TLatex(5.35,ptHist->GetMaximum()*0.01,"DATA");
  tex2->SetTextColor(2);
  tex2->SetTextSize(0.075);
  tex2->SetTextFont(42);
  tex2->Draw();
  c02->cd(2);
  etaHist->SetMaximum(etaHist->GetMaximum()*1.2);
  etaHist->SetXTitle("#eta");
  etaHist->SetYTitle("Events");
  etaHist->GetXaxis()->CenterTitle(1);
  etaHist->GetYaxis()->CenterTitle(1);
  etaHist->GetXaxis()->SetTitleOffset(0.95);
  etaHist->GetYaxis()->SetTitleOffset(1.12);
  etaHist->GetXaxis()->SetTitleSize(0.048);
  etaHist->GetYaxis()->SetTitleSize(0.048);
  etaHist->Draw("HIST");
  etaHistData->SetLineColor(2);
  etaHistData->Draw("HIST same");
  c02->cd(3);
  phiHist->SetMaximum(phiHist->GetMaximum()*1.2);
  phiHist->SetXTitle("#phi");
  phiHist->SetYTitle("Events");
  phiHist->GetXaxis()->CenterTitle(1);
  phiHist->GetYaxis()->CenterTitle(1);
  phiHist->GetXaxis()->SetTitleOffset(0.95);
  phiHist->GetYaxis()->SetTitleOffset(1.12);
  phiHist->GetXaxis()->SetTitleSize(0.048);
  phiHist->GetYaxis()->SetTitleSize(0.048);
  phiHist->Draw("HIST");
  phiHistData->SetLineColor(2);
  phiHistData->Draw("HIST same");
  c02->cd(4);
  gPad->SetLogy();
  generalTracksHist->SetMaximum(generalTracksHist->GetMaximum()*2.2);
  generalTracksHist->SetXTitle("N_{trk} (p_{T}>0.3 GeV/c)");
  generalTracksHist->SetYTitle("Events");
  generalTracksHist->GetXaxis()->CenterTitle(1);
  generalTracksHist->GetYaxis()->CenterTitle(1);
  generalTracksHist->GetXaxis()->SetTitleOffset(0.95);
  generalTracksHist->GetYaxis()->SetTitleOffset(1.12);
  generalTracksHist->GetXaxis()->SetTitleSize(0.048);
  generalTracksHist->GetYaxis()->SetTitleSize(0.048);
  generalTracksHist->Draw("HIST");
  generalTracksHistData->SetLineColor(2);
  generalTracksHistData->Draw("HIST same");
  TLatex *tex1= new TLatex(170.35,generalTracksHist->GetMaximum()*0.25,Form("<N_{trk}> = %.2f", generalTracksHist->GetMean()));
  tex1->SetTextColor(1);
  tex1->SetTextSize(0.055);
  tex1->SetTextFont(42);
  tex1->Draw();
  TLatex *tex2= new TLatex(170.35,generalTracksHist->GetMaximum()*0.075,Form("<N_{trk}> = %.2f", generalTracksHistData->GetMean()));
  tex2->SetTextColor(2);
  tex2->SetTextSize(0.055);
  tex2->SetTextFont(42);
  tex2->Draw();
  c02->SaveAs("plot_track_comp.pdf");
  c02->SaveAs("plot_track_comp.png");

//hf
  TCanvas *c03 = new TCanvas("c03","c03",1,1,770,660);
  c03->SetFillColor(10);
  c03->SetFrameFillColor(0);
  c03->SetFrameBorderSize(0);
  c03->SetFrameBorderMode(0);
  c03->SetLeftMargin(0.15);
  c03->SetBottomMargin(0.15);
  c03->SetTopMargin(0.02);
  c03->SetRightMargin(0.02);
  c03->Divide(2,2);
  gStyle->SetOptStat(0);
  c03->SetTicks(-1);
  c03->cd(1);
  gPad->SetLogy();
  hHF->SetMaximum(hHF->GetMaximum()*3.2);
  hHF->SetXTitle("Sum HF ET in 2.9<|#eta|<5.2 (GeV)");
  hHF->SetYTitle("Events");
  hHF->GetXaxis()->CenterTitle(1);
  hHF->GetYaxis()->CenterTitle(1);
  hHF->GetXaxis()->SetTitleOffset(0.95);
  hHF->GetYaxis()->SetTitleOffset(1.12);
  hHF->GetXaxis()->SetTitleSize(0.048);
  hHF->GetYaxis()->SetTitleSize(0.048);
  hHF->Draw("HIST");
  hHFData->SetLineColor(2);
  hHFData->Draw("HIST same");
  TLatex *tex1= new TLatex(140.35,hHF->GetMaximum()*0.39,"MC");
  tex1->SetTextColor(1);
  tex1->SetTextSize(0.075);
  tex1->SetTextFont(42);
  tex1->Draw();
  TLatex *tex2= new TLatex(140.35,hHF->GetMaximum()*0.15,"DATA");
  tex2->SetTextColor(2);
  tex2->SetTextSize(0.075);
  tex2->SetTextFont(42);
  tex2->Draw();
  c03->cd(2);
  gPad->SetLogy();
  hHFplus->SetMaximum(hHFplus->GetMaximum()*3.2);
  hHFplus->SetXTitle("Sum HF ET in #eta>2.9 (GeV)");
  hHFplus->SetYTitle("Events");
  hHFplus->GetXaxis()->CenterTitle(1);
  hHFplus->GetYaxis()->CenterTitle(1);
  hHFplus->GetXaxis()->SetTitleOffset(0.95);
  hHFplus->GetYaxis()->SetTitleOffset(1.12);
  hHFplus->GetXaxis()->SetTitleSize(0.048);
  hHFplus->GetYaxis()->SetTitleSize(0.048);
  hHFplus->Draw("HIST");
  hHFplusData->SetLineColor(2);
  hHFplusData->Draw("HIST same");
  c03->cd(3);
  gPad->SetLogy();
  hHFminus->SetMaximum(hHFminus->GetMaximum()*3.2);
  hHFminus->SetXTitle("Sum HF ET in #eta<-2.9 (GeV)");
  hHFminus->SetYTitle("Events");
  hHFminus->GetXaxis()->CenterTitle(1);
  hHFminus->GetYaxis()->CenterTitle(1);
  hHFminus->GetXaxis()->SetTitleOffset(0.95);
  hHFminus->GetYaxis()->SetTitleOffset(1.12);
  hHFminus->GetXaxis()->SetTitleSize(0.048);
  hHFminus->GetYaxis()->SetTitleSize(0.048);
  hHFminus->Draw("HIST");
  hHFminusData->SetLineColor(2);
  hHFminusData->Draw("HIST same");
  c03->SaveAs("plot_hf_comp.pdf");
  c03->SaveAs("plot_hf_comp.png");

//trkV
  TCanvas *c04 = new TCanvas("c04","c04",1,1,770,660);
  c04->SetFillColor(10);
  c04->SetFrameFillColor(0);
  c04->SetFrameBorderSize(0);
  c04->SetFrameBorderMode(0);
  c04->SetLeftMargin(0.15);
  c04->SetBottomMargin(0.15);
  c04->SetTopMargin(0.02);
  c04->SetRightMargin(0.02);
  c04->Divide(2,2);
  gStyle->SetOptStat(0);
  c04->SetTicks(-1);
  c04->cd(1);
  hdzOerr->SetMaximum(hdzOerr->GetMaximum()*1.2);
  hdzOerr->SetXTitle("dz/dzErr");
  hdzOerr->SetYTitle("Normalized by number of track");
  hdzOerr->GetXaxis()->CenterTitle(1);
  hdzOerr->GetYaxis()->CenterTitle(1);
  hdzOerr->GetXaxis()->SetTitleOffset(0.95);
  hdzOerr->GetYaxis()->SetTitleOffset(1.12);
  hdzOerr->GetXaxis()->SetTitleSize(0.048);
  hdzOerr->GetYaxis()->SetTitleSize(0.048);
hdzOerr->Scale(1.0/hdzOerr->GetEntries());
  hdzOerr->Draw("HIST");
hdzOerrData->Scale(1.0/hdzOerrData->GetEntries());
  hdzOerrData->SetLineColor(2);
  hdzOerrData->Draw("HIST same");
  TLatex *tex1= new TLatex(5.35,hdzOerr->GetMaximum()*0.8,"MC");
  tex1->SetTextColor(1);
  tex1->SetTextSize(0.075);
  tex1->SetTextFont(42);
  tex1->Draw();
  TLatex *tex2= new TLatex(5.35,hdzOerr->GetMaximum()*0.66,"DATA");
  tex2->SetTextColor(2);
  tex2->SetTextSize(0.075);
  tex2->SetTextFont(42);
  tex2->Draw();
  c04->cd(2);
  hd0Oerr->SetMaximum(hd0Oerr->GetMaximum()*1.2);
  hd0Oerr->SetXTitle("d0/d0Err");
  hd0Oerr->SetYTitle("Normalized by number of track");
  hd0Oerr->GetXaxis()->CenterTitle(1);
  hd0Oerr->GetYaxis()->CenterTitle(1);
  hd0Oerr->GetXaxis()->SetTitleOffset(0.95);
  hd0Oerr->GetYaxis()->SetTitleOffset(1.12);
  hd0Oerr->GetXaxis()->SetTitleSize(0.048);
  hd0Oerr->GetYaxis()->SetTitleSize(0.048);
hd0Oerr->Scale(1.0/hd0Oerr->GetEntries());
  hd0Oerr->Draw("HIST");
hd0OerrData->Scale(1.0/hd0OerrData->GetEntries());
  hd0OerrData->SetLineColor(2);
  hd0OerrData->Draw("HIST same");
  c04->cd(3);
  hpterrOpt->SetMaximum(hpterrOpt->GetMaximum()*1.2);
  hpterrOpt->SetXTitle("p_{T}Err/p_{T}");
  hpterrOpt->SetYTitle("Normalized by number of track");
  hpterrOpt->GetXaxis()->CenterTitle(1);
  hpterrOpt->GetYaxis()->CenterTitle(1);
  hpterrOpt->GetXaxis()->SetTitleOffset(0.95);
  hpterrOpt->GetYaxis()->SetTitleOffset(1.12);
  hpterrOpt->GetXaxis()->SetTitleSize(0.048);
  hpterrOpt->GetYaxis()->SetTitleSize(0.048);
hpterrOpt->Scale(1.0/hpterrOpt->GetEntries());
  hpterrOpt->Draw("HIST");
hpterrOptData->Scale(1.0/hpterrOptData->GetEntries());
  hpterrOptData->SetLineColor(2);
  hpterrOptData->Draw("HIST same");
  c04->SaveAs("plot_trkV_comp.pdf");
  c04->SaveAs("plot_trkV_comp.png");

//2Detaphi
  TCanvas *c05 = new TCanvas("c05","c05",1,1,770,330);
  c05->SetFillColor(10);
  c05->SetFrameFillColor(0);
  c05->SetFrameBorderSize(0);
  c05->SetFrameBorderMode(0);
  c05->SetLeftMargin(0.15);
  c05->SetBottomMargin(0.15);
  c05->SetTopMargin(0.02);
  c05->SetRightMargin(0.02);
  c05->Divide(2,1);
  gStyle->SetOptStat(0);
  c05->SetTicks(-1);
  c05->cd(1);
  hetaVSphi->SetXTitle("#eta");
  hetaVSphi->SetYTitle("#phi");
  hetaVSphi->GetXaxis()->CenterTitle(1);
  hetaVSphi->GetYaxis()->CenterTitle(1);
  hetaVSphi->GetXaxis()->SetTitleOffset(0.95);
  hetaVSphi->GetYaxis()->SetTitleOffset(1.12);
  hetaVSphi->GetXaxis()->SetTitleSize(0.048);
  hetaVSphi->GetYaxis()->SetTitleSize(0.048);
  hetaVSphi->SetMinimum(16);
  hetaVSphi->Draw("colz");
  TLatex *tex1= new TLatex(-0.4,3.33,"MC");
  tex1->SetTextColor(1);
  tex1->SetTextSize(0.075);
  tex1->SetTextFont(42);
  tex1->Draw();
  c05->cd(2);
  hetaVSphiData->SetXTitle("#eta");
  hetaVSphiData->SetYTitle("#phi");
  hetaVSphiData->GetXaxis()->CenterTitle(1);
  hetaVSphiData->GetYaxis()->CenterTitle(1);
  hetaVSphiData->GetXaxis()->SetTitleOffset(0.95);
  hetaVSphiData->GetYaxis()->SetTitleOffset(1.12);
  hetaVSphiData->GetXaxis()->SetTitleSize(0.048);
  hetaVSphiData->GetYaxis()->SetTitleSize(0.048);
  hetaVSphiData->SetMinimum(16);
  hetaVSphiData->Draw("colz");
  TLatex *tex1= new TLatex(-0.4,3.33,"Data");
  tex1->SetTextColor(1);
  tex1->SetTextSize(0.075);
  tex1->SetTextFont(42);
  tex1->Draw();
  c05->SaveAs("plot_2Detaphi_comp.pdf");
  c05->SaveAs("plot_2Detaphi_comp.png");


}

